title: Code Cutout
description: Scrapbook of a different class

url: http://codecutout.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: "blog/:title/"

markdown: kramdown
highlighter: rouge
gems: ["jekyll-paginate", "jekyll-redirect-from"]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: codecutout
   #twitter: brianmaierjr
   #facebook: brianmaierjr
   email: alex@codecutout.com

google_analytics: "UA-43239606-1"
